"""Cargo's half of the Rust backend: what a service's manifest depends on, and the workspace lock that pins it.

A service's dependencies follow from its selection — none for the walking skeleton, the event store's crates
once that axis is answered, and `sqlx` inside a marked region per store, so `./init --event-store memory`
takes the crate out with the adapter that used it. The lock is committed per dependency set, because Cargo
refuses (`--locked`) a lock that disagrees with the manifests, and resolving one needs the network a
generation must not. One workspace holds every Rust service, so the lock is chosen for the *union* of their
dependency sets — Cargo unifies a crate's features across the workspace, so two services on two stores need
the lock that has both — and then carries one member entry per service.
"""
from __future__ import annotations

import itertools
import re

from ...assets import LANGUAGE_ROOT
from ...selection import Selection

# The crates the event store's code imports, and how each is asked for. Pinned to the release the committed
# locks were resolved against; `scripts/regenerate-locks.py` re-resolves them when one moves.
EVENT_STORE_CRATES = {
    "serde": '{ version = "1.0.229", features = ["derive"] }',
    "serde_json": '"1.0.151"',
    "thiserror": '"2.0.21"',
    "time": '{ version = "0.3.55", features = ["formatting", "macros"] }',
    "tokio": '{ version = "1.53.1", features = ["macros", "rt-multi-thread", "sync", "time"] }',
    "uuid": '{ version = "1.26.1", features = ["v4"] }',
}
# One `sqlx` per store, in that store's marked region: a service holds exactly one store, so the two never
# meet in one manifest. Postgres also compiles its migrations into `bin/migrate`, which is `migrate!`.
SQLX_VERSION = "0.9.0"
SQLX_FEATURES = {
    "sqlite": ("runtime-tokio", "sqlite"),
    "postgres": ("runtime-tokio", "macros", "migrate", "postgres"),
}
STORES = tuple(SQLX_FEATURES)
DEPENDENCIES = "__DEPENDENCIES__"
LOCKS = LANGUAGE_ROOT / "rust/locks"
# The member name every committed lock is resolved under, replaced by each service's own.
PLACEHOLDER = "delivery-starter"


def sqlx(store: str) -> str:
    features = ", ".join(f'"{feature}"' for feature in SQLX_FEATURES[store])
    return f'sqlx = {{ version = "{SQLX_VERSION}", default-features = false, features = [{features}] }}\n'


def dependencies(selection: Selection) -> str:
    """The `[dependencies]` a service's manifest holds for this selection, with each store in its region.

    Every store's region is written and the unselected ones are cut by the same prune `./init` runs, so what
    decides which store a project has is one piece of code, not two.
    """
    if not selection.has("memory"):
        return ""
    crates = "".join(f"{name} = {spec}\n" for name, spec in EVENT_STORE_CRATES.items())
    regions = "".join(
        f"# backing-service:{store}:begin\n{sqlx(store)}# backing-service:{store}:end\n" for store in STORES
    )
    return crates + regions


def with_dependencies(manifest: str, selection: Selection) -> str:
    return manifest.replace(f"{DEPENDENCIES}\n", dependencies(selection))


def direct_crates(selection: Selection) -> list[str]:
    """The crates a service names directly — its member entry's dependencies in the lock, sorted as Cargo does."""
    if not selection.has("memory"):
        return []
    stored = any(selection.has(store) for store in STORES)
    return sorted([*EVENT_STORE_CRATES, *(["sqlx"] if stored else [])])


def lock_variant(selections: list[Selection]) -> str | None:
    """Which committed lock fits these services together, or None where none of them depends on anything."""
    if not any(selection.has("memory") for selection in selections):
        return None
    stores = [store for store in STORES if any(selection.has(store) for selection in selections)]
    return "-".join(["memory", *stores])


def empty_lock(names: list[str]) -> str:
    """The lock of a workspace that depends on nothing: each member at `0.1.0`, which Cargo writes exactly so."""
    return header() + "".join(member_entry(name, []) for name in sorted(names))


def header() -> str:
    return "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n"


def member_entry(name: str, crates: list[str]) -> str:
    listed = "".join(f' "{crate}",\n' for crate in crates)
    dependencies_line = f"dependencies = [\n{listed}]\n" if crates else ""
    return f'\n[[package]]\nname = "{name}"\nversion = "0.1.0"\n{dependencies_line}'


ENTRY = re.compile(r'\n\[\[package\]\]\nname = "([^"]+)"\nversion = "([^"]+)"\n')


def lock(members: list[tuple[str, Selection]]) -> str:
    """The workspace lock for these services: the committed lock for their union, one member entry per service.

    The committed lock carries a single member, resolved under the placeholder name with every crate the union
    names. That entry is replaced by one per service listing only its own crates, and the packages are put back
    in the order Cargo writes them — by name, then version — so `--locked` finds exactly what it would write.
    """
    variant = lock_variant([selection for _, selection in members])
    if variant is None:
        return empty_lock([name for name, _ in members])
    committed = (LOCKS / variant / "Cargo.lock").read_text()
    body = committed[len(header()):]
    starts = [match.start() for match in ENTRY.finditer(body)] + [len(body)]
    entries = [body[start:end] for start, end in itertools.pairwise(starts)]
    kept = [entry for entry in entries if ENTRY.match(entry).group(1) != PLACEHOLDER]  # type: ignore[union-attr]
    kept += [member_entry(name, direct_crates(selection)) for name, selection in members]

    def order(entry: str) -> tuple[str, tuple[int, ...]]:
        match = ENTRY.match(entry)
        assert match is not None
        return match.group(1), tuple(int(part) for part in re.findall(r"\d+", match.group(2)))

    return header() + "".join(sorted(kept, key=order))
